version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:3.3.0
    links:
     - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  beam:
    image: maven:3.5-jdk-8
    command: mvn compile
#    command: mvn compile exec:java -Dexec.mainClass=com.andrewjones.KafkaProducerExample -Pdirect-runner
    volumes:
      - .:/usr/src/kafka
      - $HOME/.m2:/root/.m2
    working_dir: /usr/src/kafka
    links:
      - kafka
